title: Marianne Bjorner
author: mbjorner
email: mbbjorner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog?

# social links
# twitter_username: your-twitter-handle
github_username:  mbjorner
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
